/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElText: typeof import('element-plus/es')['ElText']
    ExtractPrompt: typeof import('./src/components/Icons/ExtractPrompt.vue')['default']
    LeftPanel: typeof import('./src/components/LeftPanel/LeftPanel.vue')['default']
    Menu: typeof import('./src/components/Menu.vue')['default']
    MiddlePanel: typeof import('./src/components/MiddlePanel/MiddlePanel.vue')['default']
    PicturePromptPanel: typeof import('./src/components/LeftPanel/PicturePromptPanel.vue')['default']
    PromptInput: typeof import('./src/components/PromptInput.vue')['default']
    RightPanel: typeof import('./src/components/RightPanel/RightPanel.vue')['default']
    StoryPanel: typeof import('./src/components/LeftPanel/StoryPanel.vue')['default']
    Viewport: typeof import('./src/components/Viewport.vue')['default']
  }
}
